// Copyright (c) 2011 House of Life Property ltd.
// Copyright (c) 2011 Crystalnix <vgachkaylo@crystalnix.com>

#ifndef CHROME_COMMON_CHROME_RELEASE_VERSION_INFO_H_
#define CHROME_COMMON_CHROME_RELEASE_VERSION_INFO_H_

/*
#define PRODUCT_NAME "@PRODUCT_FULLNAME@"
#define PRODUCT_VERSION "@MAJOR@.@MINOR@.@BUILD@.@PATCH@"
#define LAST_CHANGE "@LASTCHANGE@"
#define OFFICIAL_BUILD @OFFICIAL_BUILD@
*/

#define CHROMIUM_RELEASE_VERSION "23.0.1271.101"

#endif  // CHROME_COMMON_CHROME_RELEASE_VERSION_INFO_H_
